#5183 Add locale strings for legends in forms
pkp/ojs pull request #2803
Opened 2020-06-11 01:27 UTC by thinkbulecount2

From this issue: https://github.com/pkp/pkp-lib/issues/5183

2020-06-11 08:51 UTC, NateWr requested changes
Looks good. I left a few comments. In addition, let's move the new locale keys into pkp-lib. They can go into `common.po`. 

With that change, you shouldn't need any PRs for OMP or OPS. But go ahead and test the pkp-lib changes in OMP and OPS just to make sure.

2020-06-11 08:51 UTC, NateWr commented on locale/en_US/locale.po
> +msgstr "Option to consent"
Let's use "Privacy Options".

2020-06-11 08:51 UTC, NateWr commented on templates/frontend/pages/purchaseIndividualSubscription.tpl
> +				{translate key="user.subscriptions.form.typeId"}
Use `payment.subscription.purchase` ("Purchase Subscription")

2020-06-11 08:51 UTC, NateWr commented on templates/frontend/pages/purchaseInstitutionalSubscription.tpl
> +				{translate key="user.subscriptions.form.typeId"}
Use `payment.subscription.purchase` ("Purchase Subscription")

2020-09-29 15:25 UTC, thinkbulecount2 commented
cc: @NateWr

2020-09-29 15:49 UTC, NateWr commented on locale/en_US/locale.po
> +
All of the new locale keys in this PR are available in pkp-lib so they can be removed here.

2020-09-29 15:49 UTC, NateWr commented on templates/frontend/pages/purchaseIndividualSubscription.tpl
> +							{translate key="payment.subscription.purchase"}
I think this should stay as `user.subscriptions.form.typeId`. That would make the legend "Purchase Subscription" and this particular field "Subscription Type".

2020-09-29 15:49 UTC, NateWr commented on templates/frontend/pages/purchaseInstitutionalSubscription.tpl
> +				{translate key="user.subscriptions.form.typeId"}
It looks like this still hasn't been done.

2020-09-30 01:49 UTC, thinkbulecount2 commented
Made changes, @NateWr.

2020-09-30 09:05 UTC, CLAassistant commented
[![CLA assistant check](https://cla-assistant.io/pull/badge/not_signed)](https://cla-assistant.io/pkp/ojs?pullRequest=2803) <br/>Thank you for your submission! We really appreciate it. Like many open source projects, we ask that you all sign our [Contributor License Agreement](https://cla-assistant.io/pkp/ojs?pullRequest=2803) before we can accept your contribution.<br/>**1** out of **2** committers have signed the CLA.<br/><br/>:white_check_mark: thinkbulecount2<br/>:x: NateWr<br/><sub>You have signed the CLA already but the status is still pending? Let us [recheck](https://cla-assistant.io/check/pkp/ojs?pullRequest=2803) it.</sub>

2020-09-30 09:09 UTC, merged