set urlPath when importing galleys via NativeXML
pkp/ojs pull request #2957
Opened 2020-12-19 11:49 UTC by eocarragain

This pull request aims to fix bug reported https://github.com/pkp/pkp-lib/issues/6501 ("Galley url_path not imported in Native XML Import/Export")

I have tested it on OJS 3.2.1-1 and it produces the desired result, i.e. imported galleys now have the url_path specified in the article_galley element in the xml.

Feedback very welcome. Thanks

2020-12-19 11:49 UTC, CLAassistant commented
[![CLA assistant check](https://cla-assistant.io/pull/badge/not_signed)](https://cla-assistant.io/pkp/ojs?pullRequest=2957) <br/>Thank you for your submission! We really appreciate it. Like many open source projects, we ask that you sign our [Contributor License Agreement](https://cla-assistant.io/pkp/ojs?pullRequest=2957) before we can accept your contribution.<br/><sub>You have signed the CLA already but the status is still pending? Let us [recheck](https://cla-assistant.io/check/pkp/ojs?pullRequest=2957) it.</sub>

2020-12-19 12:35 UTC, eocarragain commented
1 of the 5 CI jobs failed but, from the log, it seems to have been an unrelated issue with starting Chrome?

2020-12-22 08:45 UTC, defstat requested changes
Along with the review change, please check whether the exported XML file you are using, actually has the `url_path` attribute in its `article_galley` node. If it does not, we should consider adding the export line, like `$representationNode->setAttribute('url_path', $representation->getData('urlPath'));` in the `createRepresentationNode` function of the `RepresentationNativeXmlFilter` export filter.

2020-12-22 08:45 UTC, defstat commented on plugins/importexport/native/filter/NativeXmlArticleGalleyFilter.inc.php
> +		$representation->setData('urlPath', $node->getAttribute('url_path'));
Try adding this line at `NativeXmlRepresentationFilter`, which is the parent class. That way your change will go into the PKP-LIB project, effecting all applications (OJS, OMP, OPS). Moreover, the `url_path` attribute is declared here (https://github.com/pkp/pkp-lib/blob/master/plugins/importexport/native/pkp-native.xsd#L224) which resides at PKP-LIB project.

2020-12-30 22:18 UTC, eocarragain commented
thanks @defstat 

That all makes sense. See new pull request against pkp-lib here: https://github.com/pkp/pkp-lib/pull/6521

Closing this pull request in favour of https://github.com/pkp/pkp-lib/pull/6521

2020-12-30 22:18 UTC, closed without merging