pkp/pkp-lib#6140 Displaying Upgrade section at OJS installation within a notification component
pkp/ojs pull request #2985
Opened 2021-01-12 01:02 UTC by henriqueramos

# What was made?

Added the upgrade section at OJS installation within a notification component.

# Evidences
## Current Version
![103529433-6e59b100-4e64-11eb-8d93-a3e0266b2d33](https://user-images.githubusercontent.com/1243634/104255726-77e0ab80-5458-11eb-8699-470dc2d73351.png)

## Updated Version
![Screenshot from 2021-01-11 21-48-32](https://user-images.githubusercontent.com/1243634/104255771-90e95c80-5458-11eb-9084-7730e004b941.png)

2021-01-12 10:19 UTC, NateWr requested changes
Great! Just the one comment on the localized string.

2021-01-12 10:19 UTC, NateWr commented on locale/en_US/locale.po
> +"<notification>\nIf you are upgrading an existing installation of OJS, <pkp-button element=\"a\" href=\"{$upgradeUrl}\">click here</pkp-button> to proceed.</notification>\n"
Let's move the `<notification>` tag out of the translation code. That can go directly into here: https://github.com/pkp/pkp-lib/pull/6571/files#diff-68710e4a718cc0c14dbdb1cfe373f032481bd8d26d42f08d6851499e3bcd860eR18.

Also, let's change `<pkp-button>` to the `<a>` element. I think the link will be prominent enough once the whole notice is in the `<notification>` element.

2021-01-12 10:19 UTC, NateWr commented on locale/en_US/locale.po
> +"<notification>\nIf you are upgrading an existing installation of OJS, <pkp-button element=\"a\" href=\"{$upgradeUrl}\">click here</pkp-button> to proceed.</notification>\n"
(The line breaks can also be removed.)

2021-01-13 05:16 UTC, henriqueramos commented
# Updated version

![Screenshot from 2021-01-13 02-15-19](https://user-images.githubusercontent.com/1243634/104409553-498cca00-5545-11eb-92ee-7f92aa092885.png)

2021-01-14 11:00 UTC, merged