pkp/pkp-lib#6567 fix journal section deletion
pkp/ojs pull request #2996
Opened 2021-01-17 14:23 UTC by bozana

s. https://github.com/pkp/pkp-lib/issues/6567

2021-01-18 20:40 UTC, asmecher requested changes

2021-01-18 20:40 UTC, asmecher commented on controllers/grid/settings/sections/SectionGridHandler.inc.php
> +		$checkSubmissions = $submissionDao->retrieve('SELECT p.publication_id FROM publications p JOIN submissions s ON (s.submission_id = p.submission_id) WHERE p.section_id = ? AND s.context_id = ?', [(i
The grid handlers shouldn't be executing SQL directly; this should be moved into the DAO.

2021-01-19 11:16 UTC, bozana commented
@asmecher, I added a new SectionDAO function sectionEmpty and removed the old one that seems not to be used getEmptyByJournalId. OK so?

2021-01-19 17:51 UTC, asmecher commented
Looks good, thanks, please go ahead! Feel free to start exploring the Laravel query builder toolset for new queries (https://laravel.com/docs/7.x/queries) -- we'll want to gradually move everything over to using it.

2021-01-19 17:52 UTC, asmecher commented
(However, it does look like the tests failed! Worth a look before merging.)

2021-01-23 14:13 UTC, merged