pkp/pkp-lib#7592 Refactor reviewer-related emails
pkp/ojs pull request #3300
Opened 2022-02-15 19:20 UTC by Vitaliy-1

2022-03-08 14:21 UTC, NateWr requested changes

2022-03-08 14:21 UTC, NateWr commented on locale/en_US/manager.po
> +msgstr "Information about a subscriber, including user full name, affiliation, phone number and email"
> The subscriber's name, affiliation, phone number and email address

2022-03-08 14:21 UTC, NateWr commented on locale/en_US/manager.po
> +msgstr "The link to the subscription page"
> The URL to the subscription page

2022-03-08 14:21 UTC, NateWr commented on locale/en_US/manager.po
> +msgstr "The end date of the subscription"
> The date when the subscription ends

2022-03-08 14:21 UTC, NateWr commented on locale/en_US/manager.po
> +msgstr "subscription type summary, containing name, duration and cost"
A summary of the subscription's type, name, duration and cost

2022-03-08 14:21 UTC, NateWr commented on locale/en_US/manager.po
> +msgstr "subscription membership information"
Information about the subscriber's membership

2022-03-16 18:37 UTC, Vitaliy-1 commented on locale/ar_IQ/emails.po
> -msgid "emails.reviewRequestAttached.subject"
Yes, rebasing was a pain

2022-03-16 18:48 UTC, Vitaliy-1 commented on classes/mail/variables/SubscriptionEmailVariable.inc.php
> +            self::MEMBERSHIP => 'emailTemplate.variable.subscription.membership',
oops

2022-04-02 15:28 UTC, Vitaliy-1 commented
@NateWr, it looks like the error during tests is due to `ui-library` not being synced with the current OJS main branch.

2022-04-04 09:21 UTC, NateWr commented
Have you tried to pull the latest changes from the ui-library in and add them to your submodule commit? The text of the emaili template in the logs looks like none of the email variables are being changed, which suggests something maybe more significant is off here:

https://app.travis-ci.com/github/pkp/ojs/jobs/565390269#L2663

I don't think `{$submissionTitle}` or `{$signature}` would appear in the email composer without being rendered based on a recent commit. If you sync everything up and still run into a test failure, let me know and I'll look into it further.

2022-04-07 13:59 UTC, merged