Feature/main/8627 ignore missing files native xml
pkp/ojs pull request #3780
Opened 2023-02-17 12:47 UTC by jonasraoni

2023-02-28 16:14 UTC, defstat requested changes

2023-02-28 19:30 UTC, jonasraoni commented on plugins/importexport/native/filter/NativeFilterHelper.php
> +        return $coversNode->firstChild?->parentNode;
Yes, just a shortcut of `$coversNode->firstChild ? $coversNode : null;`, I'll change to make it easier to read.

2023-03-01 09:52 UTC, jonasraoni commented on plugins/importexport/native/filter/NativeFilterHelper.php
> +        return $coversNode->firstChild?->parentNode;
Okay, so I'll leave it 😅
This [requires PHP 8](https://wiki.php.net/rfc/nullsafe_operator), and stable-3_3_0 has tests against PHP 7.3.

2023-03-01 10:24 UTC, CLAassistant commented
[![CLA assistant check](https://cla-assistant.io/pull/badge/not_signed)](https://cla-assistant.io/pkp/ojs?pullRequest=3780) <br/>Thank you for your submission! We really appreciate it. Like many open source projects, we ask that you sign our [Contributor License Agreement](https://cla-assistant.io/pkp/ojs?pullRequest=3780) before we can accept your contribution.<br/><sub>You have signed the CLA already but the status is still pending? Let us [recheck](https://cla-assistant.io/check/pkp/ojs?pullRequest=3780) it.</sub>

2023-03-01 11:26 UTC, merged