pkp/pkp-lib#9823 update the crontrol job processing via scheduler
pkp/ojs pull request #4364
Opened 2024-07-12 08:28 UTC by touhidurabir

for pkp/pkp-lib#9823

2024-08-01 12:51 UTC, jonasraoni commented on docs/release-notes/README-3.5.0
> +    - schedule_job_process (default value: On), control the process of queue jobs via task scheduler
```suggestion
    - schedule_job_process (default value: Off): Controls whether queued jobs should be processed by the task scheduler.
```

2024-08-01 14:54 UTC, jonasraoni requested changes
@touhidurabir Just minor changes, I think the setting name is difficult for me to understand, so I've suggested alternatives.

2024-08-02 07:53 UTC, touhidurabir commented on config.TEMPLATE.inc.php
> +; schedule_job_process = On
@jonasraoni 
> Another alternative would be to move this setting to the [schedule] group as process_queued_jobs = On|Off

I think it's better to keep in within `queue` section as it's a queue jobs execution control option .

> suggest changing the name

I agree the current name is bit difficult to understand and the purpose it serve. My motivation was to keep the name bit small but I also think it makes it bit harder to understand. I agree with changing the name as you proposed .

2024-08-02 09:10 UTC, jonasraoni commented on config.TEMPLATE.inc.php
> +; schedule_job_process = On
Ok! I'll approve everything 😁

2024-08-02 09:10 UTC, jonasraoni approved these changes

2024-08-02 09:40 UTC, merged