pkp/pkp-lib#9910 Use UI Language in Announcement Feeds
pkp/ojs pull request #4368
Opened 2024-07-16 14:34 UTC by bozana

s. https://github.com/pkp/pkp-lib/issues/9910

2024-07-16 17:24 UTC, jonasraoni requested changes
This is very similar to the https://github.com/pkp/webFeed/pull/3, so the same comment can be applied here.

2025-01-13 13:33 UTC, jonasraoni requested changes

2025-01-13 13:33 UTC, jonasraoni commented on plugins/generic/announcementFeed/AnnouncementFeedGatewayPlugin.php
> +            'language' => str_replace(['_', '@'], '-', Locale::getLocale()),
I've seen this in other places, I think it should be a method somewhere ` toBcp47()`?!

2025-01-13 13:33 UTC, jonasraoni commented on plugins/generic/announcementFeed/templates/rss.tpl
> +		<dc:language>{$language|escape}</dc:language>
As the `$language` doesn't depend on the `$context->getPrimaryLocale()` (which I guess should be always available anyway), then the `{if}` can be removed.

2025-01-13 13:33 UTC, jonasraoni commented on plugins/generic/announcementFeed/templates/rss2.tpl
> +			<language>{$language|escape}</language>
As the `$language` doesn't depend on the `$context->getPrimaryLocale()` (which I guess should be always available anyway), then the `{if}` can be removed.

2025-01-13 15:09 UTC, bozana commented on plugins/generic/announcementFeed/AnnouncementFeedGatewayPlugin.php
> +            'language' => str_replace(['_', '@'], '-', Locale::getLocale()),
s. https://github.com/pkp/pkp-lib/issues/10795

2025-01-13 18:47 UTC, merged