pkp/pkp-lib#10139 fix Author search pulls in keywords too
pkp/ojs pull request #4380
Opened 2024-07-29 00:47 UTC by Hafsa-Naeem

2024-07-29 00:47 UTC, CLAassistant commented
[![CLA assistant check](https://cla-assistant.io/pull/badge/not_signed)](https://cla-assistant.io/pkp/ojs?pullRequest=4380) <br/>Thank you for your submission! We really appreciate it. Like many open source projects, we ask that you sign our [Contributor License Agreement](https://cla-assistant.io/pkp/ojs?pullRequest=4380) before we can accept your contribution.<br/><sub>You have signed the CLA already but the status is still pending? Let us [recheck](https://cla-assistant.io/check/pkp/ojs?pullRequest=4380) it.</sub>

2024-07-29 15:42 UTC, asmecher commented
@jonasraoni, could you review this one?

2024-07-31 22:12 UTC, jonasraoni requested changes
@Hafsa-Naeem I've left two comments, but as I'll replace this code with https://github.com/pkp/ojs/pull/4224, I think you just need to update the `$sqlWhere .= ' AND (o.type & ?) != 0';` part.

2024-07-31 22:12 UTC, jonasraoni commented on classes/search/ArticleSearchDAO.inc.php
> +		if (!empty($type) && $type == SUBMISSION_SEARCH_AUTHOR) {
The previous code was incorrect (or perhaps outdated), assuming that we would a bitmask, but I didn't understand why you've limited the type to `SUBMISSION_SEARCH_AUTHOR`.

2024-08-07 14:34 UTC, jonasraoni requested changes
@Hafsa-Naeem The problem should be fixed after the latest update.

Just one thing... Alec asked to avoid touching sensible parts of the code on the `stable` branches, to avoid breaking the toy (our tests are not covering everything), unless it's something really important. So, can you drop the not needed updates? I guess only the line 50 is needed (I know it's painful 😤).

Then, you can create the PRs for the other applications (if the problem exists on them) and port to `stable-3_4_0` and `main`. (or if you prefer, I can just cherry-pick the commits).

2025-08-05 13:29 UTC, jonasraoni approved these changes

2025-08-05 13:29 UTC, jonasraoni commented on classes/search/ArticleSearchDAO.inc.php
> +           }
```suggestion
           $sqlWhere .= $type == SUBMISSION_SEARCH_AUTHOR ? ' AND o.type = ?' : ' AND (o.type & ?) != 0';
```

2026-05-11 12:23 UTC, closed without merging