pkp/pkp-lib#10157 Move issueIds out of of publication_settings
pkp/ojs pull request #4396
Opened 2024-08-12 07:53 UTC by Hafsa-Naeem

fix [#10157](https://github.com/pkp/pkp-lib/issues?q=assignee%3AHafsa-Naeem+is%3Aopen)

2024-08-12 07:53 UTC, CLAassistant commented
[![CLA assistant check](https://cla-assistant.io/pull/badge/not_signed)](https://cla-assistant.io/pkp/ojs?pullRequest=4396) <br/>Thank you for your submission! We really appreciate it. Like many open source projects, we ask that you sign our [Contributor License Agreement](https://cla-assistant.io/pkp/ojs?pullRequest=4396) before we can accept your contribution.<br/><sub>You have signed the CLA already but the status is still pending? Let us [recheck](https://cla-assistant.io/check/pkp/ojs?pullRequest=4396) it.</sub>

2024-08-12 20:23 UTC, jonasraoni requested changes
@Hafsa-Naeem Besides the comments, you'll need to create a migration in the `classes/migration/upgrade/v3_5_0` folder to:
- Create the field for users which are upgrading from OJS < 3.5
- The field should be filled with the content from the `publication_settings`
- The data from the `publication_settings` must be cleared.

Take a look at the file /dbscripts/xml/upgrade.xml.

2024-08-12 20:23 UTC, jonasraoni commented on classes/migration/upgrade/v3_4_0/I7901_Duplicate_OAI_IDs.php
> +                    JOIN issues i ON (i.issue_id = p.issue_id)
This PR is for the 3.5, you don't need to touch older upgrade scripts. At this point your new field will not exist yet.

2024-08-12 20:23 UTC, jonasraoni commented on classes/migration/upgrade/v3_4_0/PreflightCheckMigration.php
> +            $rows = DB::table('publications AS p')
The same as above, you don't need to touch the upgrade scripts for versions < 3.5.

2024-08-12 20:23 UTC, jonasraoni commented on classes/search/ArticleSearchDAO.php
> +                JOIN issues i ON (i.issue_id = p.issue_id AND i.journal_id = s.context_id)
You forgot to remove the line below. Also, I think we can trust enough in the code to drop the `AND i.journal_id = s.context_id`

2024-08-12 20:23 UTC, jonasraoni commented on classes/oai/ojs/OAIDAO.php
> +            ->join('issues AS i', 'i.issue_id', '=', 'p.issue_id')
You forgot to remove the line below.

2024-08-12 20:23 UTC, jonasraoni commented on classes/services/queryBuilders/StatsGeoQueryBuilder.php
>              });
Hmm, I think this join (also appear at the next file (`classes/services/queryBuilders/StatsPublicationQueryBuilder.php`), would be better written with a `whereExists()`, but as it's not part of your task, you might ignore.

2024-08-12 20:23 UTC, jonasraoni commented on classes/submission/Collector.php
>              });
The parent class has a join (i.e. `publications AS po`) that you might use, and it will greatly simplify these lines of code.

2025-02-26 19:09 UTC, asmecher requested changes
Hi @Hafsa-Naeem! The upgrade process needs some work but overall the shape looks good.

2025-02-26 19:09 UTC, asmecher commented on classes/migration/upgrade/v3_5_0/I10157_CreateAndMigrateIssueIdField.php
> +        DB::statement('UPDATE publications p JOIN publication_settings ps ON p.publication_id = ps.publication_id AND ps.setting_name = "issueId" SET p.issue_id = ps.setting_value');
Also, I don't think this clause will work with PostgreSQL as formatted.

2025-02-26 19:09 UTC, asmecher commented on dbscripts/xml/upgrade.xml
> +		<migration class="APP\migration\upgrade\v3_5_0\I10157_CreateAndMigrateIssueIdField.php"/>
This doesn't appear to be working; see the [test failure on the upgrade test](https://github.com/pkp/ojs/actions/runs/13537527205/job/37831790207?pr=4396):
![image](https://github.com/user-attachments/assets/08048b38-2a00-4c46-84cf-6e13ec21b3a1)

2025-02-26 19:09 UTC, asmecher commented on classes/migration/upgrade/v3_5_0/I10157_CreateAndMigrateIssueIdField.php
> +    public function up(): void
This adds the column, but does not add the FK constraint that would be created on a fresh install.

2025-02-26 19:09 UTC, asmecher commented on classes/oai/ojs/OAIDAO.php
> +            ->join('issues AS i', 'i.issue_id', '=', 'p.issue_id')
This comment still hasn't been resolved.

2025-02-27 00:13 UTC, Hafsa-Naeem commented on classes/oai/ojs/OAIDAO.php
> +            ->join('issues AS i', 'i.issue_id', '=', 'p.issue_id')
I've reviewed the changes, and there are no remaining references to `psissue` or publication_settings in this method. The old join using publication_settings was removed, and the issues table is now correctly joined using p.issue_id. Is there a specific line that still needs to be removed?

2025-02-27 00:50 UTC, asmecher commented on classes/oai/ojs/OAIDAO.php
> +            ->join('issues AS i', 'i.issue_id', '=', 'p.issue_id')
I think it's an out-of-date comment; resolving.

2025-02-27 23:26 UTC, asmecher commented on classes/submission/Collector.php
> +            $q->whereIn('po.issue_id', $this->issueIds);
This change (and the one to the section filter below) changes the meaning of the query. Previously, it searched for submissions with any publication in the specified issue or section; now, it only fetches results where the *current* publication is in the specified section or issue. I think this change is probably unintentional, right?

2025-02-27 23:32 UTC, asmecher commented on classes/migration/upgrade/v3_5_0/I10157_CreateAndMigrateIssueIdField.php
> +        if (DB::getDriverName() === 'pgsql') {
Lately we've been relying on code more like...
```php
use Illuminate\Database\MariaDbConnection;
use Illuminate\Database\MySqlConnection;
use Illuminate\Database\PostgresConnection;

...

switch (true) {
    case DB::connection() instanceof PostgresConnection:
        // Do a PostgreSQL query
        break;
    case DB::connection() instanceof MySqlConnection:
    case DB::connection() instanceof MySqlConnection:
        // Do a MySQL/MariaDB query
        break;
    default: throw new \Exception('Unknown database driver');
}
```
This is much more resilient than the string comparison.

2025-02-28 19:21 UTC, asmecher commented
Manually merged to resolve submodule conflict (25cf1cc3d62fa96c44631b4d022ab263ca1eeaae)

2025-02-28 19:21 UTC, closed without merging