pkp/pkp-lib#10263 Relax editing metadata on published/posted materials
pkp/ojs pull request #4410
Opened 2024-08-26 07:52 UTC by Hafsa-Naeem

for [#10263](https://github.com/pkp/pkp-lib/issues/10263)

2024-08-26 07:53 UTC, CLAassistant commented
[![CLA assistant check](https://cla-assistant.io/pull/badge/not_signed)](https://cla-assistant.io/pkp/ojs?pullRequest=4410) <br/>Thank you for your submission! We really appreciate it. Like many open source projects, we ask that you sign our [Contributor License Agreement](https://cla-assistant.io/pkp/ojs?pullRequest=4410) before we can accept your contribution.<br/><sub>You have signed the CLA already but the status is still pending? Let us [recheck](https://cla-assistant.io/check/pkp/ojs?pullRequest=4410) it.</sub>

2025-01-28 11:51 UTC, defstat requested changes
@Hafsa-Naeem thanks for the changes! this could be a tricky feature, involving many code parts. 

I am trying the change on my local installation and it seems that I can't hit "save" button when the publication is published.

if you see at the picture bellow, the "Save" button is "disabled".

![image](https://github.com/user-attachments/assets/53d92ac8-dfff-465b-8b99-a1fae6bfaf28)

Also are there PRs for OMP? 

Lastly, I can see that the tests are failing. Is that ready for the tests also?

2025-02-28 17:51 UTC, defstat requested changes
Thanks @Hafsa-Naeem! 2 questions on that:

1. I suppose that all metadata should be editable, including Contributors, Galleys etc. If that is true, have you considered them for this fix?

2. As asked [here](https://github.com/pkp/ojs/pull/4410#pullrequestreview-2577988967), shouldn't OMP, OPS be also considered?

3. In the current tests there are the older version's text (like `This version has been published and can not be edited.`) for published Versions, and perhaps the older version's restrictions (like disabled fields, buttons not showing etc). You also need to consider those.

2025-02-28 20:33 UTC, asmecher requested changes

2025-02-28 20:33 UTC, asmecher commented on locale/en/submission.po
>  msgid "publication.editDisabled"
This locale key is also used for presentation to the author, where editing will still be disabled in some cases, so this key should be left as-is and a new locale key created for the editor case.

2025-03-17 19:06 UTC, asmecher reviewed
Hi @Hafsa-Naeem! A partial review with a few comments.

2025-03-17 19:15 UTC, asmecher commented on cypress/tests/data/60-content/AmwandengaSubmission.cy.js
> +		// cy.get('button').contains('Save').should('be.disabled');
This should just be removed rather than commented.

2025-03-17 19:15 UTC, asmecher commented on cypress/tests/data/60-content/AmwandengaSubmission.cy.js
> -		// cy.get('#contributors button').contains('Save').should("not.be.visible");
This should be removed entirely.

2025-03-17 19:16 UTC, asmecher commented on cypress/tests/data/60-content/AmwandengaSubmission.cy.js
> -		cy.contains('This version has been published and can not be edited.');
I'm not sure if the new warning text appears here -- but if it does, there should be a Cypress check for it.

2025-03-17 19:16 UTC, asmecher commented on cypress/tests/data/60-content/VkarbasizaedSubmission.cy.js
> -		cy.contains('This version has been published and can not be edited.');
I'm not sure if the new warning text appears here -- but if it does, there should be a Cypress check for it.

2025-03-20 19:33 UTC, asmecher commented on locale/fa/submission.po
> +
@Hafsa-Naeem, all of these unnecessary edits should be removed from the PR.

2026-05-11 12:24 UTC, closed without merging