pkp/pkp-lib#4787 Reviewer suggestions
pkp/ojs pull request #4459
Opened 2024-10-03 07:33 UTC by touhidurabir

for pkp/pkp-lib#4787

2024-11-04 09:38 UTC, touhidurabir commented on classes/migration/upgrade/v3_5_0/I4787_ReviewSuggestions.php
> +}
This should probably go to a `v3_6_0`  folder .

2024-11-04 09:39 UTC, touhidurabir commented on dbscripts/xml/install.xml
> +	<migration class="PKP\migration\install\ReviewerSuggestionsMigration" />
For now , this is only a place holder as this should be a part of `3.6.0` upgrade process .

2025-02-01 17:29 UTC, defstat requested changes
thanks @touhidurabir! Only some wording comments for this one.

2025-02-14 12:22 UTC, defstat approved these changes
Thanks @touhidurabir, just one minor wording comment on your discretion.

2025-02-14 12:22 UTC, defstat commented on locale/en/default.po
> +"<p>When submitting your article, you have the option to suggest 2/3 potential "
is this "2/3 potential reviewers" the correct wording here?

2025-02-17 05:01 UTC, touhidurabir commented on locale/en/default.po
> +"<p>When submitting your article, you have the option to suggest 2/3 potential "
This is taken from what provided in the design but I think you are right , better to say it like `you have the option to suggest several potential reviewers`  .  Or you have anything better in mind .

2025-02-25 07:48 UTC, defstat requested changes
Just one comment regarding the migrations @touhidurabir, thanks! After that I think it will be ok to get merged :tada:

Also is the `registry/uiLocaleKeysBackend.json` supposed to be committed as part of this PR?

2025-02-25 07:48 UTC, defstat commented on dbscripts/xml/upgrade.xml
> +		<migration class="APP\migration\upgrade\v3_5_0\I4787_AddReviewSuggestionHelp"/>
@touhidurabir I am not sure `I4787_AddReviewSuggestionHelp` and  `I4787_InstallReviewerSuggestion` are in the correct folder. I find them under `v3_6_0`

2025-02-25 08:01 UTC, touhidurabir commented on dbscripts/xml/upgrade.xml
> +		<migration class="APP\migration\upgrade\v3_5_0\I4787_AddReviewSuggestionHelp"/>
Weird , I can see those migrations in `v3_5_0` folder .  Also tests seems to be passing as if in wrong folder , tests would have failed at upgrade stage for not being able to find the migration file .

2025-02-25 08:35 UTC, defstat commented on dbscripts/xml/upgrade.xml
> +		<migration class="APP\migration\upgrade\v3_5_0\I4787_AddReviewSuggestionHelp"/>
Maybe rebasing all branches onto main will solve that, along with the submodule conflicts? 

Just to clarify, I am always getting the PRs found here: https://github.com/pkp/pkp-lib/issues/4787#issue-447125184

Correct?

2025-02-25 08:49 UTC, defstat commented on dbscripts/xml/upgrade.xml
> +		<migration class="APP\migration\upgrade\v3_5_0\I4787_AddReviewSuggestionHelp"/>
@touhidurabir it was my bad, I correctly see the migrations in 3_5_0 now. Check this, though, if you can, regarding the conflicted submodules and json file. Thanks!!

2025-02-26 18:24 UTC, closed without merging