pkp/pkp-lib#10653 remove deprecated submission functions in OAI class…
pkp/ojs pull request #4543
Opened 2024-12-06 16:06 UTC by kaitlinnewson

…es and templates

2024-12-09 09:19 UTC, bozana requested changes
Hi @kaitlinnewson, 
the most of the data now belongs to the publication object, so instead of using $article->getData() we would need $currentPublication->getData(). Some places have it correct, but lots of them still don't.

2024-12-10 19:39 UTC, kaitlinnewson commented
Hi @bozana, ready for a second look!

2024-12-11 09:41 UTC, bozana commented on plugins/oaiMetadataFormats/marc/OAIMetadataFormat_MARC.php
> +        $representations = $representationDao->getByPublicationId($publication->getId());
Why do we need this?

2024-12-11 09:45 UTC, bozana commented on plugins/oaiMetadataFormats/marc/templates/record.tpl
> +	{foreach from=$representations item=galley}
Could we use `$publication->getData('galleys');` here?

2024-12-11 09:47 UTC, bozana commented on plugins/oaiMetadataFormats/marcxml/templates/record.tpl
> +	{if $publication->getStoredPubId('doi')}
We now use `$publication->getDoi()`.
`getStoredPubId('doi')` is old -- from the time when DOI was a plugin.

2024-12-11 10:00 UTC, bozana reviewed
Hi @kaitlinnewson, great!
Maybe one comment only -- if we can use `$publication->getData('galleys');` instead of getting the galleys anew.
And I see here is a mix of all kinds of locales in these plugins, so I created a new issue to address that https://github.com/pkp/pkp-lib/issues/10683.
Thanks a lot!

2024-12-11 13:45 UTC, kaitlinnewson commented
@bozana fixed now!

2024-12-12 11:37 UTC, merged